import 'dotenv/config'; // load .env

export const KAFKA_TOPICS = {
  LEAVE_REQUEST_CREATED: process.env.KAFKA_LEAVE_REQUEST_CREATED || '',
  LEAVE_REQUEST_CREATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_CREATED_DLQ || '',
  LEAVE_REQUEST_UPDATED: process.env.KAFKA_LEAVE_REQUEST_UPDATED || '',
  LEAVE_REQUEST_UPDATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_UPDATED_DLQ || '',
  LEAVE_REQUEST_STATUS_UPDATED:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED || '',
  LEAVE_REQUEST_STATUS_UPDATED_DLQ:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED_DLQ || '',
  USER_ACTION_REQUESTED: process.env.KAFKA_USER_ACTION_REQUESTED || '',
  USER_ACTION_REQUESTED_DLQ: process.env.KAFKA_USER_ACTION_REQUESTED_DLQ || '',
  USER_ACTION_VALIDATED: process.env.KAFKA_USER_ACTION_VALIDATED || '',
  USER_ACTION_VALIDATED_DLQ: process.env.KAFKA_USER_ACTION_VALIDATED_DLQ || '',
} as const;

export const KAFKA_DLQ_MAP: Record<string, string> = {
  [KAFKA_TOPICS.LEAVE_REQUEST_CREATED]: KAFKA_TOPICS.LEAVE_REQUEST_CREATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_UPDATED]: KAFKA_TOPICS.LEAVE_REQUEST_UPDATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED]:
    KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED_DLQ,
  [KAFKA_TOPICS.USER_ACTION_REQUESTED]: KAFKA_TOPICS.USER_ACTION_REQUESTED_DLQ,
  [KAFKA_TOPICS.USER_ACTION_VALIDATED]: KAFKA_TOPICS.USER_ACTION_VALIDATED_DLQ,
};
