import 'dotenv/config'; // load .env

export const KAFKA_TOPICS = {
  LEAVE_REQUEST_CREATED: process.env.KAFKA_LEAVE_REQUEST_CREATED || '',
  LEAVE_REQUEST_CREATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_CREATED_DLQ || '',
  LEAVE_REQUEST_UPDATED: process.env.KAFKA_LEAVE_REQUEST_UPDATED || '',
  LEAVE_REQUEST_UPDATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_UPDATED_DLQ || '',
  LEAVE_REQUEST_STATUS_UPDATED:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED || '',
  LEAVE_REQUEST_STATUS_UPDATED_DLQ:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED_DLQ || '',
  REACTION_EVENTS: process.env.KAFKA_REACTION_EVENTS || '',
  REACTION_EVENTS_DLQ: process.env.KAFKA_REACTION_EVENTS_DLQ || '',
  CANDIDATE_HIRED: process.env.KAFKA_CANDIDATE_HIRED || 'candidate.hired',
  CANDIDATE_HIRED_DLQ: process.env.KAFKA_CANDIDATE_HIRED_DLQ || 'candidate.hired.dlq',
} as const;

export const KAFKA_DLQ_MAP: Record<string, string> = {
  [KAFKA_TOPICS.LEAVE_REQUEST_CREATED]: KAFKA_TOPICS.LEAVE_REQUEST_CREATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_UPDATED]: KAFKA_TOPICS.LEAVE_REQUEST_UPDATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED]:
    KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED_DLQ,
  [KAFKA_TOPICS.REACTION_EVENTS]: KAFKA_TOPICS.REACTION_EVENTS_DLQ,
  [KAFKA_TOPICS.CANDIDATE_HIRED]: KAFKA_TOPICS.CANDIDATE_HIRED_DLQ,
};
